In [1]:
#importing the numpy library
import numpy as np

In [2]:
#setting up the seed
np.random.seed(42)

In [3]:
#generating a random vector, matrix and tensor
vector = np.random.randint( 10, size = 6)
matrix = np.random.randint ( 10, size = ( 3, 4))
tensor = np.random.randint ( 10 , size = ( 3, 4, 5 ))

In [4]:
vector

array([6, 3, 7, 4, 6, 9])

In [5]:
matrix

array([[2, 6, 7, 4],
       [3, 7, 7, 2],
       [5, 4, 1, 7]])

In [6]:
tensor

array([[[5, 1, 4, 0, 9],
        [5, 8, 0, 9, 2],
        [6, 3, 8, 2, 4],
        [2, 6, 4, 8, 6]],

       [[1, 3, 8, 1, 9],
        [8, 9, 4, 1, 3],
        [6, 7, 2, 0, 3],
        [1, 7, 3, 1, 5]],

       [[5, 9, 3, 5, 1],
        [9, 1, 9, 3, 7],
        [6, 8, 7, 4, 1],
        [4, 7, 9, 8, 8]]])

In [8]:
#visualizing their dimensions
print( f' vector − {vector.ndim}')
print( f' matrix − {matrix.ndim}')
print( f' tensor − {tensor.ndim}')

 vector − 1
 matrix − 2
 tensor − 3


In [9]:
#visualizing their shapes
print( f' vector − {vector.shape}')
print( f' matrix − {matrix.shape}')
print( f' tensor − {tensor.shape}')

 vector − (6,)
 matrix − (3, 4)
 tensor − (3, 4, 5)


In [10]:
#visualizing their sizes
print( f' vector − {vector.size}')
print( f' matrix − {matrix.size}')
print( f' tensor − {tensor.size}')

 vector − 6
 matrix − 12
 tensor − 60


In [11]:
#data type of the vector
vector.dtype

dtype('int32')

In [12]:
#using indexes on arrays
vector[0]

6

In [13]:
matrix[0]

array([2, 6, 7, 4])

In [14]:
tensor[0]

array([[5, 1, 4, 0, 9],
       [5, 8, 0, 9, 2],
       [6, 3, 8, 2, 4],
       [2, 6, 4, 8, 6]])

In [16]:
matrix[0][1]

6

In [19]:
tensor[0][1][4]

2

In [20]:
#first 3 elements of the array
vector[:3]

array([6, 3, 7])

In [21]:
#all every 2 elements
vector[::2]

array([6, 7, 6])

In [23]:
#only even columns
matrix[:, ::2]

array([[2, 7],
       [3, 7],
       [5, 1]])

In [24]:
#only the first half of columns
matrix[:, :3]

array([[2, 6, 7],
       [3, 7, 7],
       [5, 4, 1]])

In [25]:
#changing a value 
vector[1] = 99
vector

array([ 6, 99,  7,  4,  6,  9])

In [26]:
#changing more values
matrix [:, 0] = np.zeros(3)

In [27]:
matrix

array([[0, 6, 7, 4],
       [0, 7, 7, 2],
       [0, 4, 1, 7]])

In [28]:
#zero filled vector
np.zeros(3)

array([0., 0., 0.])

In [29]:
#zero filled matrix
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
#ones filled vector
np.ones(3)

array([1., 1., 1.])

In [31]:
#ones filled matrix
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
#this is a fake copy of an array
fake_copy = vector

In [34]:
print(id(fake_copy))
print(id(vector))

2531772746848
2531772746848


In [35]:
#this is a real copy of an array
real_copy = vector.copy()

In [36]:
print(id(real_copy))
print(id(vector))

2531773643072
2531772746848


In [38]:
vector[0] = 99

In [39]:
#by creating a fake copy you are sticking another sticker to the box
print(vector)
print(real_copy)
print(fake_copy)

[99 99  7  4  6  9]
[ 6 99  7  4  6  9]
[99 99  7  4  6  9]


In [40]:
#concatenation of a vector
x1 = np.array([1, 2, 3])
x2 = np.array([4, 5, 6])
np.concatenate([x1, x2])

array([1, 2, 3, 4, 5, 6])

In [41]:
#concatenation of a matrix
matrix = np.array([[1, 2, 3],[4, 5, 6]])
np.concatenate([matrix, matrix])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [42]:
#stack vertically arrays
x = np.array([1, 2, 3])
grid = np.array([[4, 5, 6],[7, 8, 9]])
np.vstack([x, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
#stack horizontally arrays
x = np.array([[ 99 ], [ 99 ]])
np.hstack([x, grid])

array([[99,  4,  5,  6],
       [99,  7,  8,  9]])

In [44]:
#splitting an array
x = np.array([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
first, second = np.split(x, [5])
first

array([1, 2, 3, 4, 5])

In [45]:
second

array([ 6,  7,  8,  9, 10])

In [46]:
#creating a matrix
matrix = np.arange(16).reshape((4, 4))
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
#splitting on a vertical axis
upper, lower = np.vsplit(matrix, [2])

In [48]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [49]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [50]:
#splitting on a horizontal axis
left, right = np.hsplit(matrix, [2])

In [51]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [52]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [55]:
def compute_inverse(values):
    #np.empty generates an empty array that can be filled after 
    out = np.empty(len(values))
    for i in range(len(values)):
        #computin the inverse
        out[i] = 1.0 / values[i]
    return out

In [56]:
values = np.random.randint( 1, 10, size = 5)
computeinverse(values)

array([1.        , 0.125     , 0.125     , 0.33333333, 1.        ])

In [57]:
big_array = np.random.randint(1, 100, size = 1000000)

In [60]:
#measuring how long it takes for the cell to run
%%timeit -n 1 -r 1
compute_inverse(big_array)

4.16 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [61]:
#how long it takes numpy to do it
%%timeit -n 1 -r 1
print(1.0 / big_array)

[0.125      0.02857143 0.02857143 ... 0.02       0.09090909 0.01041667]
6.45 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [62]:
#creating an ordered array
x = np.arange(10)

In [63]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
#addition
x + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [68]:
#substraction
x - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [67]:
#multiplication
x * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [69]:
#division
x / 4

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25])

In [70]:
# floor division
x // 4

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2], dtype=int32)

In [71]:
x ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [72]:
x % 3

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0], dtype=int32)

In [73]:
#numpy
#addition
np.add(x, 2)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [76]:
#substraction
np.subtract(x, 2)

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [77]:
#multiplication
np.multiply(x, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [78]:
#division
np.divide(x, 4)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25])

In [80]:
#floor division
np.floor_divide(x, 4)

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2], dtype=int32)

In [81]:
#power
np.power(x, 2)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [82]:
#mod
np.mod(x, 3)

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0], dtype=int32)

In [87]:
#absolute value
x = np.array([0, -1, 2, -3, -4, -5, 6, 7, 8, 9])
abs(x)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
np.absolute(x)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
np.abs(x)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
x = np.random.random(100)

In [91]:
x

array([0.94246305, 0.90809787, 0.30829823, 0.07541285, 0.45684936,
       0.45911108, 0.98387226, 0.788516  , 0.82948323, 0.05866519,
       0.73779015, 0.41425653, 0.1390659 , 0.63274185, 0.8397513 ,
       0.50112975, 0.82243518, 0.95960739, 0.69508526, 0.16384447,
       0.39285934, 0.97803683, 0.11432019, 0.14439511, 0.99243693,
       0.83730484, 0.90310265, 0.3032827 , 0.46461951, 0.69317212,
       0.16809046, 0.1293037 , 0.92975433, 0.87575531, 0.15431614,
       0.73694536, 0.58762029, 0.26854487, 0.31496562, 0.27925196,
       0.86750038, 0.1265844 , 0.27301479, 0.28748263, 0.86923281,
       0.43991381, 0.57170028, 0.48866832, 0.32302852, 0.27059472,
       0.89762553, 0.72866725, 0.67302116, 0.49219424, 0.92828503,
       0.38617134, 0.25550028, 0.73857229, 0.99215422, 0.44516222,
       0.69041818, 0.21033487, 0.80472719, 0.47356404, 0.97418272,
       0.85375244, 0.14600414, 0.410685  , 0.6906934 , 0.11353877,
       0.51628763, 0.58091506, 0.89581771, 0.87993057, 0.24566

In [92]:
#sum of elements
np.sum(x)

53.61596393222919

In [93]:
#minimal value
np.min(x)

0.03408400044630544

In [95]:
#maximum value
np.max(x)

0.9924369280116836

In [96]:
#mean value
np.mean(x)

0.5361596393222919

In [97]:
#median value
np.median(x)

0.5087086870180744

In [98]:
#creating a random array with 2 columns and 5 rows
x2 = np.random.random((5, 2))

In [99]:
x2

array([[0.12583801, 0.88380128],
       [0.1624099 , 0.63861793],
       [0.85031049, 0.13421567],
       [0.80839459, 0.39809619],
       [0.18267203, 0.61944264]])

In [100]:
#the minimum value of every row
x2.min(axis = 1)

array([0.12583801, 0.1624099 , 0.13421567, 0.39809619, 0.18267203])

In [101]:
#the minimum value of every column
x2.min(axis = 0)

array([0.12583801, 0.13421567])

In [102]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b)

32

In [103]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [105]:
np.dot(matrix, a)

array([14, 32])