In [1]:
#Importing needed libraries
import numpy as np
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [2]:
class LogisticRegression2():
    #Define a Linear Regression class to store our relevant functions in
    def __init__(self, learning_rate: float = 0.05, max_iter: int = 100000) -> None:
        '''
        The constructor of the Logistic Regression model.
            :param learning_rate: float, default = 0.05
                The learning rate of the model.
            :param max_iter: int, default = 1000000
                The number of iteration to go through.
        '''
        #Setting up the hyperparameters.
        self.__learning_rate = learning_rate
        self.__max_iter = max_iter
    def sigmoid( self, y: 'np.array') -> 'np.array':
        '''
        The sigmoid function.
        :param y: numpy.ndarray
            The predictions of the linear function .
        '''
        return 1 / (1 + np.exp(-y))
    def fit( self, X: 'np.array', y: 'np.array') -> 'LogisticRegression2':
        '''
        The fit function of the model.
        : param X : 2-D numpy.ndarray
            The X matrix with the features.
        : param y : 1-D numpy.ndarray
            The target vector.
        '''
        #Creating the weights vector
        self.coef_ = np.zeros( len(X[0]) + 1)
        #Adding the intercept column.
        X = np.hstack((X, np.ones((len(X), 1))))
        #The weights updating process.
        for i in range(self.__max_iter):
            #Prediction.
            pred = self.sigmoid(np.dot(X, self.coef_))
            
            #Computing the gradient.
            gradient = np.dot(X.T, (pred - y)) / y.size
            
            #Updating the weights.
            self.coef_ -= gradient * self.__learning_rate
        return self
    def predict_proba( self, X: 'np.array') -> 'np.array':
        '''
        This function returns the class probabilities.
        : param X : 2-D numpy.ndarray
            The X matrix with the features.
        : return : 2-D numpy.ndarray
            The array with the probabilities for every class and sample.
        '''
        
        #Adding the intercept column.
        X = np.hstack((X, np.ones((len(X), 1))))
        
        #Computing the probabilities.
        prob = self.sigmoid(np.dot(X, self.coef_))
        
        #Returning the probabilities.
        return np.hstack(((1 - prob).reshape(-1, 1), prob.reshape(-1, 1)))

    def predict( self, X: 'np.array') -> 'np.array':
        '''
        This functions returns the predictions.
        : param X : 2-D numpy.ndarray
            The X matrix with the features.
        : return : 2-D numpy.ndarray
            The array with the predictions
        '''
        
        #Adding the intercept column.
        X = np.hstack((X, np.ones((len(X), 1))))
        
        return ( self.sigmoid(np.dot(X, self.coef_)) > 0.7 ) * 1





## Logistic Regression implimentation from Sklearn library

In [4]:
#Getting the feature matrix and target vector from iris data set.
X, y = load_iris(return_X_y = True)

In [5]:
#Splitting the data in train and test with train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [6]:
#Creating the model
clf = LogisticRegression( random_state = 0)

In [7]:
#Fitting the model
clf.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [8]:
#Making predictions
y_pred = clf.predict(X_test)

In [9]:
#Visualizing the confusion matrix
confusion_matrix(y_test, y_pred)

array([[19,  0,  0],
       [ 0, 13,  0],
       [ 0,  0, 13]], dtype=int64)

In [10]:
#Visualizing accuracy score
accuracy_score(y_test, y_pred)

1.0

#### We have a 100% accuracy score - LogisticRegression predicted everything correctly

In [11]:
#Implimentation of our model on iris dataset
gr = LogisticRegression2()

In [12]:
#The sigmoid function from our model
gr.sigmoid( y )

array([0.5       , 0.5       , 0.5       , 0.5       , 0.5       ,
       0.5       , 0.5       , 0.5       , 0.5       , 0.5       ,
       0.5       , 0.5       , 0.5       , 0.5       , 0.5       ,
       0.5       , 0.5       , 0.5       , 0.5       , 0.5       ,
       0.5       , 0.5       , 0.5       , 0.5       , 0.5       ,
       0.5       , 0.5       , 0.5       , 0.5       , 0.5       ,
       0.5       , 0.5       , 0.5       , 0.5       , 0.5       ,
       0.5       , 0.5       , 0.5       , 0.5       , 0.5       ,
       0.5       , 0.5       , 0.5       , 0.5       , 0.5       ,
       0.5       , 0.5       , 0.5       , 0.5       , 0.5       ,
       0.73105858, 0.73105858, 0.73105858, 0.73105858, 0.73105858,
       0.73105858, 0.73105858, 0.73105858, 0.73105858, 0.73105858,
       0.73105858, 0.73105858, 0.73105858, 0.73105858, 0.73105858,
       0.73105858, 0.73105858, 0.73105858, 0.73105858, 0.73105858,
       0.73105858, 0.73105858, 0.73105858, 0.73105858, 0.73105

In [13]:
#The fit function from our model
gr.fit(X_train, y_train)

In [14]:
#The predict_proba from our model, returning the probabilities
gr.predict_proba(X_test)

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [18]:
#The predict function that returns the predictions
y_pred = gr.predict(X_test)

In [19]:
#Visualizing the confusion matrix
confusion_matrix(y_test, y_pred)

array([[ 0, 19,  0],
       [ 0, 13,  0],
       [ 0, 13,  0]], dtype=int64)

In [20]:
#Visualizing accuracy score
accuracy_score(y_test, y_pred)

0.28888888888888886

##### Our Logistic Regression model predicted only the second class 